// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2fg-K50Q_XLnLM6MziYzHR8_zZo0JrSI',
    appId: '1:1038756800282:web:ab40b4553787cf96f3aea3',
    messagingSenderId: '1038756800282',
    projectId: 'instagram-remake-67dc6',
    authDomain: 'instagram-remake-67dc6.firebaseapp.com',
    storageBucket: 'instagram-remake-67dc6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY6KbPxDW9fhm56KmL7D1GU2RnOBhbA6c',
    appId: '1:1038756800282:android:601016f8a46356b6f3aea3',
    messagingSenderId: '1038756800282',
    projectId: 'instagram-remake-67dc6',
    storageBucket: 'instagram-remake-67dc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMNee7JWh9f6-E0fCaLVFgQbbcE6QLDHE',
    appId: '1:1038756800282:ios:5865fae0c03cf7c6f3aea3',
    messagingSenderId: '1038756800282',
    projectId: 'instagram-remake-67dc6',
    storageBucket: 'instagram-remake-67dc6.appspot.com',
    iosClientId: '1038756800282-od84h0cj0qd3r7jf1iu5kfikonfpsgir.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramRemake',
  );
}
